// Code generated by "stringer -type packetType"; DO NOT EDIT.

package ioconn

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[undefined-0]
	_ = x[ack-1]
	_ = x[synAck-2]
	_ = x[fin-3]
	_ = x[finAck-4]
	_ = x[data-5]
}

const _packetType_name = "undefinedacksynAckfinfinAckdata"

var _packetType_index = [...]uint8{0, 9, 12, 18, 21, 27, 31}

func (i packetType) String() string {
	if i >= packetType(len(_packetType_index)-1) {
		return "packetType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _packetType_name[_packetType_index[i]:_packetType_index[i+1]]
}
